Neural network implementation for the mask detection task

In [1]:
# Modules required for the Neural Network implementation
import torch

In [59]:
## Initialize Linear model
L = torch.nn.Linear(in_features=768, out_features=1,
                    bias=True)

tensor([[-0.0233, -0.0170, -0.0278,  0.0316,  0.0157, -0.0070,  0.0255,  0.0092,
          0.0182, -0.0013]], grad_fn=<SliceBackward0>)


In [60]:
## Define training data

# inputs need to have samples on rows with columns
# representing features: shape (X,768), where 768 is the number of features
input_data = # as array_like
train_input = torch.as_tensor(input_data, dtype=torch.float)
#train_input = torch.randn(100,768)

# Target is a column vector of 0s and 1s: shape (X,1)
target_data = # as array_like
train_target = torch.as_tensor(target_data, dtype=torch.float)
#train_target = torch.empty(100,1).random_(2)

In [61]:
## Network training algorithm

# Learning rate of the SGD algorithm
learning_rate = 0.01

# Forward pass
output = L(train_input)

# BCE loss function with sigmoid activation
lossfunc = torch.nn.BCEWithLogitsLoss()

# Compute loss
loss = lossfunc(output, train_target)

# Create Stochastic Gradient Descent optimizer
SDGoptimizer = torch.optim.SGD(L.parameters(), lr=learning_rate)

# Backward pass
loss.backward()

# Update weights
SDGoptimizer.step()

print(L.weight[:,0:10])

tensor([[-0.0235, -0.0171, -0.0265,  0.0314,  0.0154, -0.0063,  0.0256,  0.0083,
          0.0180, -0.0016]], grad_fn=<SliceBackward0>)


In [67]:
## Testing environment

# inputs need to have samples on rows with columns
# representing features: shape (X,768), where 768 is sample size
test_input = torch.randn(100,768)

test_output = L(test_input)

print(test_output)

tensor([[ 0.5649],
        [-0.0187],
        [-0.0829],
        [-0.0494],
        [-0.6876],
        [ 0.9663],
        [ 0.8508],
        [-0.3855],
        [ 0.3558],
        [ 0.3628],
        [ 0.2391],
        [-0.0678],
        [-0.7487],
        [-0.1698],
        [-1.2731],
        [-0.1548],
        [ 0.3579],
        [-0.1737],
        [-1.5329],
        [-0.2743],
        [ 0.2982],
        [ 0.9333],
        [ 0.1864],
        [ 0.8170],
        [ 0.8964],
        [-0.0585],
        [-0.3428],
        [ 0.2939],
        [-0.0965],
        [-0.6837],
        [ 0.8751],
        [-0.6481],
        [-0.1714],
        [-0.1831],
        [-0.3113],
        [-0.1187],
        [ 0.4026],
        [-0.0810],
        [ 0.6237],
        [ 0.6879],
        [ 0.1635],
        [-0.2261],
        [ 0.0930],
        [ 0.6435],
        [ 0.3392],
        [ 0.6612],
        [-0.7135],
        [ 0.2555],
        [-0.4106],
        [ 0.0424],
        [-0.0172],
        [-0.0282],
        [ 0.