Neural network implementation for the mask detection task

In [42]:
# Modules required for the Neural Network implementation
import torch
import torcheval

In [43]:
## Initialize Linear model
L = torch.nn.Linear(in_features=768, out_features=1,
                    bias=True)

In [44]:
## Define training data

# inputs need to have samples on rows with columns
# representing features: shape (X,768), where 768 is the number of features
#input_data = # as array_like
#train_input = torch.as_tensor(input_data, dtype=torch.float)
X_train = torch.randn(1000,768) # random input

# Target is a column vector of 0s and 1s: shape (X,1)
#target_data = # as array_like
#train_target = torch.as_tensor(target_data, dtype=torch.float)
#train_target = torch.empty(1000,1).random_(2) # random labels
y_train = torch.zeros([1000,1])
for i in range(len(X_train)):
    if X_train[i,0] >= 0:
        y_train[i] = 1
    else:
        y_train[i] = 0

In [45]:
# Model fitting functions for mask detection
learning_rate = 0.01

def fit(L, X_train, y_train, batch_size, n_iter, lr):
    
    for i_batch in range(n_iter):
        batch_indices = torch.randint(len(X_train), [batch_size])
        train_batch(L, X_train[batch_indices], y_train[batch_indices], lr)


def train_batch(L, X_batch, y_batch, lr):
    lossfunc = torch.nn.BCEWithLogitsLoss()
    optimizer = torch.optim.SGD(L.parameters(), lr=lr)
    loss_diary = torch.zeros([len(X_batch)])

    for i in range(len(X_batch)):
        output = L(X_train[i])
        loss = lossfunc(output, y_train[i])
        loss.backward()
        optimizer.step()

    mean_loss = torch.mean(loss_diary)
    print(mean_loss)

In [47]:
fit(L, X_train, y_train, 10, 100, 0.01)


tensor(0.)
tensor(0.)
tensor(0.)
tensor(0.)
tensor(0.)
tensor(0.)
tensor(0.)
tensor(0.)
tensor(0.)
tensor(0.)
tensor(0.)
tensor(0.)
tensor(0.)
tensor(0.)
tensor(0.)
tensor(0.)
tensor(0.)
tensor(0.)
tensor(0.)
tensor(0.)
tensor(0.)
tensor(0.)
tensor(0.)
tensor(0.)
tensor(0.)
tensor(0.)
tensor(0.)
tensor(0.)
tensor(0.)
tensor(0.)
tensor(0.)
tensor(0.)
tensor(0.)
tensor(0.)
tensor(0.)
tensor(0.)
tensor(0.)
tensor(0.)
tensor(0.)
tensor(0.)
tensor(0.)
tensor(0.)
tensor(0.)
tensor(0.)
tensor(0.)
tensor(0.)
tensor(0.)
tensor(0.)
tensor(0.)
tensor(0.)
tensor(0.)
tensor(0.)
tensor(0.)
tensor(0.)
tensor(0.)
tensor(0.)
tensor(0.)
tensor(0.)
tensor(0.)
tensor(0.)
tensor(0.)
tensor(0.)
tensor(0.)
tensor(0.)
tensor(0.)
tensor(0.)
tensor(0.)
tensor(0.)
tensor(0.)
tensor(0.)
tensor(0.)
tensor(0.)
tensor(0.)
tensor(0.)
tensor(0.)
tensor(0.)
tensor(0.)
tensor(0.)
tensor(0.)
tensor(0.)
tensor(0.)
tensor(0.)
tensor(0.)
tensor(0.)
tensor(0.)
tensor(0.)
tensor(0.)
tensor(0.)
tensor(0.)
tensor(0.)
tensor(0.)

In [48]:
## Testing environment

# inputs need to have samples on rows with columns
# representing features: shape (X,768), where 768 is sample size
X_test = torch.randn(500,768)
y_test = torch.zeros([500, 1])
for i in range(len(X_train)):
    if X_train[i,0] >= 0:
        y_train[i] = 1
    else:
        y_train[i] = 0

y_prob = torch.sigmoid(L(X_test))
y_pred = torch.round(y_prob)

correct = 0
for i in range(len(y_pred)):
    if y_pred[i] == y_test[i]:
        correct += 1
accuracy = correct/len(y_pred)

print(y_prob[0:10,:])
print(y_pred[0:10,:])
print(accuracy)

tensor([[0.0000e+00],
        [0.0000e+00],
        [5.1029e-20],
        [0.0000e+00],
        [0.0000e+00],
        [8.5619e-25],
        [0.0000e+00],
        [0.0000e+00],
        [1.0000e+00],
        [0.0000e+00]], grad_fn=<SliceBackward0>)
tensor([[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.]], grad_fn=<SliceBackward0>)
0.516


In [50]:
print(X_test[0:10,0])

tensor([-0.6053,  0.2663,  0.0590, -2.6686, -3.0597, -1.7991,  0.7897, -1.3379,
         0.1080,  0.8870])
