Neural network implementation for the mask detection task

In [2]:
# Modules required for the Neural Network implementation
import torch

In [3]:
## Initialize Linear model
L = torch.nn.Linear(in_features=768, out_features=1,
                    bias=True)

In [4]:
## Define training data

# inputs need to have samples on rows with columns
# representing features: shape (X,768), where 768 is the number of features
#input_data = # as array_like
#train_input = torch.as_tensor(input_data, dtype=torch.float)
train_input = torch.randn(1000,768) # random input

# Target is a column vector of 0s and 1s: shape (X,1)
#target_data = # as array_like
#train_target = torch.as_tensor(target_data, dtype=torch.float)
train_target = torch.empty(1000,1).random_(2) # random labels

In [5]:
## Network training algorithm

# Learning rate of the SGD algorithm
learning_rate = 0.01

# Forward pass
output = L(train_input)

# BCE loss function with sigmoid activation
lossfunc = torch.nn.BCEWithLogitsLoss()

# Compute loss
loss = lossfunc(output, train_target)

# Create Stochastic Gradient Descent optimizer
SDGoptimizer = torch.optim.SGD(L.parameters(), lr=learning_rate)

# Backward pass
loss.backward()

# Update weights
SDGoptimizer.step()

print(L.weight[:,0:10])

tensor([[ 7.0922e-05, -2.7705e-02,  1.9984e-02, -1.9095e-02,  1.1072e-02,
         -2.0419e-02,  2.3635e-02,  1.9698e-02,  1.6660e-02,  9.3722e-03]],
       grad_fn=<SliceBackward0>)


In [9]:
## Testing environment

# inputs need to have samples on rows with columns
# representing features: shape (X,768), where 768 is sample size
test_input = torch.randn(100,768)

test_output_prob = torch.sigmoid(L(test_input))
test_output_pred = torch.round(test_output_prob)

print(test_output_prob[0:10,:])
print(test_output_pred[0:10,:])

tensor([[0.7438],
        [0.5547],
        [0.6098],
        [0.5092],
        [0.4348],
        [0.4138],
        [0.4926],
        [0.4514],
        [0.4395],
        [0.3345]], grad_fn=<SliceBackward0>)
tensor([[1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.]], grad_fn=<SliceBackward0>)
